"""new fields in user model

Revision ID: 004e99287403
Revises: 90a5cdf116bd
Create Date: 2020-08-27 16:52:59.418838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004e99287403'
down_revision = '90a5cdf116bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
